# ------------------
# Project Paths
# ------------------
paths:
  fcs_data_dir: "../data/fcs/"
  cache_dir: "cache/"
  output_dir: "output/"
  plot_filename: "interactive_umap_plot.html"

# ------------------
# Logging Configuration
# ------------------
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "cyto-plot.log"

# ------------------
# Data Processing Settings
# ------------------
data_processing:
  # Max events to load per file. Set to -1 to load all events.
  max_events_per_file: 6_000
  # Columns to exclude from UMAP analysis.
  # 'filename' is added during loading for labeling purposes.
  exclude_columns:
    - "Time"
    - "filename"

# ------------------
# UMAP Algorithm Parameters
# See cuML and umap-learn docs for details
# ------------------
umap_params:
  n_neighbors: 100
  min_dist: 0.1
  n_components: 2
