# ------------------
# Project Paths
# ------------------
paths:
  fcs_data_dir: "../data/fcs/"
  cache_dir: "cache/"
  output_dir: "output/"
  plot_filename: "interactive_umap_plot.html"

# ------------------
# Logging Configuration
# ------------------
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "cyto-plot.log"

# ------------------
# Data Processing Settings
# ------------------
data_processing:
  # Max events to load per file. Set to -1 to load all events.
  max_events_per_file: 6_000 # For more than 6000 points the UMAP is always noisy
  # Columns to exclude from UMAP analysis.
  # 'filename' is added during loading for labeling purposes.
  exclude_columns:
    - "Time"
    - "filename"

# ------------------
# UMAP Algorithm Parameters
# See cuML and umap-learn docs for details
# ------------------
umap_params_clustering:
  n_neighbors: 80
  min_dist: 0.1
  n_components: 4 # Higher dimension for clustering

umap_params_visualization:
  n_neighbors: 50 # Higher n_neighbors for better global structure
  min_dist: 0.1 # Higher min_dist for better separation
  n_components: 2 # 2D for plotting

# ------------------
# DBSCAN Clustering Parameters
# See cuML docs for details
# ------------------
dbscan_params:
  eps: 0.4 # Neighborhood of a point, Higher eps for larger clusters
  min_samples: 100 # Higher min_samples for more robust clusters
